plugins{
    id 'java'
}

group 'com.sandtiger.research'
version '1.0-SNAPSHOT'

jar{
    manifest {
        attributes(
            'Main-Class': 'com.sandtiger.research.Game'
        )
    }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test {
    useJUnitPlatform()
}